const data = [
  {
    name: "Ohi Marwa",
    id: 2046823,
    roll: "01",
    image: "src/image.jpg",
    details: {
      father: "Abdullah Al Mamun",
      mother: "Mosammat Shahina Akter",
      religion: "Islam",
    },
  },
  {
    name: "Istat Nahar Mimmi",
    id: 2021623,
    roll: "02",
    image: "src/image002.jpg",
    details: {
      father: "Md Yousuf Ali",
      mother: "Nurun Naha",
      religion: "Islam",
    },
  },
  {
    name: "Mst Fowjia Akter",
    id: 2020923,
    roll: "03",
    image: "src/image003.jpg",
    details: {
      father: "Md Ali Akmut",
      mother: "Kamrunnahar",
      religion: "Islam",
    },
  },
  {
    name: "FATHEHA SARMIN TANISHA",
    id: 2022823,
    roll: "04",
    image: "src/image004.jpg",
    details: {
      father: "MOHAMMAD MOKTER HOSSAIN BHUYAN",
      mother: "FARHANA AKTAR PANNA",
      religion: "Islam",
    },
  },
  {
    name: "Md Mahmud Hasan Bhuiyan",
    id: 2020623,
    roll: "05",
    image: "src/image005.jpg",
    details: {
      father: "Md Belaet Hossain Bhuiyan",
      mother: "Shamima Nasrin",
      religion: "Islam",
    },
  },
  {
    name: "Asma Akter Bristi",
    id: 2045623,
    roll: "06",
    image: "src/image006.jpg",
    details: {
      father: "Md Anisur Rahman",
      mother: "Parvin Begum",
      religion: "Islam",
    },
  },
  {
    name: "Nabila Islam",
    id: 2066323,
    roll: "07",
    image: "src/image007.jpg",
    details: {
      father: "Md Nourul Islam Miazee",
      mother: "Somi Akter",
      religion: "Islam",
    },
  },
  {
    name: "Monira Tabassum",
    id: 2045423,
    roll: "08",
    image: "src/image008.jpg",
    details: {
      father: "Monirul Islam",
      mother: "Rousan Akter",
      religion: "Islam",
    },
  },
  {
    name: "Shah Mohsen Rezan",
    id: 2019023,
    roll: "09",
    image: "src/image009.jpg",
    details: {
      father: "Md Shahjahan",
      mother: "Mahmuda Akter",
      religion: "Islam",
    },
  },
  {
    name: "Afifa Chowdhury",
    id: 2076723,
    roll: "10",
    image: "src/image010.jpg",
    details: {
      father: "Md Abdul Qayyum Chowdhury",
      mother: "Shahida gum",
      religion: "Islam",
    },
  },
  {
    name: "Safayet Islam",
    id: 2047123,
    roll: "11",
    image: "src/image011.jpg",
    details: {
      father: "Mohammad Idris Miah",
      mother: "Mrs Surma Sultana",
      religion: "Islam",
    },
  },
  {
    name: "Fahmida ltana",
    id: 2022423,
    roll: "12",
    image: "src/image012.jpg",
    details: {
      father: "Abdul Motaleb",
      mother: "Shahina Akter",
      religion: "Islam",
    },
  },
  {
    name: "Ornab Banik",
    id: 2020723,
    roll: "13",
    image: "src/image013.jpg",
    details: {
      father: "Nantu Banik",
      mother: "Monika Banik",
      religion: "Islam",
    },
  },
  {
    name: "Al Arafat Siyam",
    id: 2076923,
    roll: "14",
    image: "src/image014.jpg",
    details: {
      father: "Md Halal Uddin",
      mother: "Shamsun Nahar",
      religion: "Islam",
    },
  },
  {
    name: "Jannatul Ferdoush",
    id: 2022923,
    roll: "15",
    image: "src/image015.jpg",
    details: {
      father: "Shomon Miah",
      mother: "Taslima Begum",
      religion: "Islam",
    },
  },
  {
    name: "Sakibul Alam Khan Fahad",
    id: 2046523,
    roll: "16",
    image: "src/image016.jpg",
    details: {
      father: "Fakhrul Alam",
      mother: "Parvin Akter",
      religion: "Islam",
    },
  },
  {
    name: "Rimi Akter",
    id: 2021723,
    roll: "17",
    image: "src/image017.jpg",
    details: {
      father: "Rahomot Ulla",
      mother: "Sanowara Begum",
      religion: "Islam",
    },
  },
  {
    name: "Ommey Aymon Tonni",
    id: 2022723,
    roll: "18",
    image: "src/image018.jpg",
    details: {
      father: "Md. Tahidullam",
      mother: "Nazrin Nahar",
      religion: "Islam",
    },
  },
  {
    name: "Nusrat Jahan Akhi",
    id: 2077123,
    roll: "19",
    image: "src/image019.jpg",
    details: {
      father: "Md Nasir Uddin",
      mother: "Pervin Akhter Panna",
      religion: "Islam",
    },
  },
      {
    name: "Farhana Akhter Mily",
    id: 2022623,
    roll: "21",
    image: "src/image021.jpg",
    details: {
      father: "Md Mijanur Rahman",
      mother: "Narkis Begum",
      religion: "Islam",
    },
  },    {
    name: "Sumiya Akter Shati",
    id: 2022023,
    roll: "22",
    image: "src/image022.jpg",
    details: {
      father: "Helal Ahmed",
      mother: "Hashina Akter",
      religion: "Islam",
    },
  },    {
    name: "Md Nabil Hossain",
    id: 2046323,
    roll: "23",
    image: "src/image023.jpg",
    details: {
      father: "Sah Jamal Mia",
      mother: "Rina Begum",
      religion: "Islam",
    },
  },    {
    name: "Jannatul Mawa Minha",
    id: 2072423,
    roll: "24",
    image: "src/image024.jpg",
    details: {
      father: "Md Milon",
      mother: "Suria Begum",
      religion: "Islam",
    },
  },    {
    name: "Muradul Islam Shaun",
    id: 2020823,
    roll: "25",
    image: "src/image025.jpg",
    details: {
      father: "Shiraj",
      mother: "Lutfur Nahar",
      religion: "Islam",
    },
  },    {
    name: "Ishrat Jahan Mitu",
    id: 2019923,
    roll: "26",
    image: "src/image026.jpg",
    details: {
      father: "Md Jamal Hossain",
      mother: "Ayesha Begum",
      religion: "Islam",
    },
  },    {
    name: "Sakibul Hasan",
    id: 2021023,
    roll: "27",
    image: "src/image027.jpg",
    details: {
      father: "Md Jahangir Alom",
      mother: "Miss Sahira Begum",
      religion: "Islam",
    },
  },    {
    name: "Tania Akter",
    id: 2023123,
    roll: "28",
    image: "src/image028.jpg",
    details: {
      father: "Abdur Rob",
      mother: "Nasima Akter",
      religion: "Islam",
    },
  },    {
    name: "Tasmia Binte Ferdaus",
    id: 2022523,
    roll: "29",
    image: "src/image029.jpg",
    details: {
      father: "Md Ferdaushul Alom",
      mother: "Taslima Akter",
      religion: "Islam",
    },
  },
    {
    name: "Md Tahmid Moontasir Saowmoon",
    id: 2019123,
    roll: "30",
    image: "src/image030.jpg",
    details: {
      father: "Md Kamal Hossain",
      mother: "Kazi Khadizatul Kobra",
      religion: "Islam",
    },
  },
];
